#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Workaround for https://github.com/typicode/husky/issues/671
function exit_proxy(){
   if [ "$?" -ne 0 ] 
   then
      exit 1
   fi

   exit 0
}
trap exit_proxy EXIT

lint-staged
